apiVersion: apps/v1
kind: Deployment
metadata:
  name: artx
spec:
  selector:
    matchLabels:
      app: artx
  template:
    metadata:
      labels:
        app: artx
    spec:
      containers:
        - name: artx
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_8c11a9b31968
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: artx-volume
              mountPath: /app/images
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql:3306/artx"
            - name: DDL_AUTO
              value: "none"
            - name: IMAGE_DIRECTORY
              value: "/app/images"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOG_LEVEL
              value: "INFO"
            - name: KAKAOPAY_CID
              value: "TC0ONETIME"
            - name: KAKAOPAY_ADMIN_KEY
              value: "94c0f2e2624cf70ae98d3d9568104683"
            - name: PROXY_HOST
              value: "krmp-proxy.9rum.cc"
            - name: PROXY_PORT
              value: "3128"
            - name: ARTX_HOST
              value: "https://ka8d596e67406a.user-app.krampoline.com"
            - name: ARTX_PORT
              value: "80"
            - name: ARTX_ADDRESS
              value: "https://ka8d596e67406a.user-app.krampoline.com"
            - name: JWT_SECRET
              value: "6db7d12ce6b83355585381ecdd90f4b62e250db79fb0b4eb61d6c4c1ca5ff183e0d8a8f4701f71ebec37580b083a72cf2860a327c9345cf60f937aaba07ac041v"
            - name: GMAIL_USERNAME
              value: "dlwodud821@gmail.com"
            - name: GMAIL_PASSWORD
              value: "eutf hszs dvsa qylp"
            - name: DATASOURCE_INIT
              value: "true"
            - name: SQL_INIT_MODE
              value: "never"
      volumes:
        - name: artx-volume
          persistentVolumeClaim:
            claimName: artx-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: artx
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: artx